### ISSUE TITLE
Custom GCloud Binary Location

### ISSUE THREAD

**Issue by asdptkt** [mrwbsn/kaosmangki#1]
Hi, I think you need to add customizable GCloud binary location. Possibly through an environment variable.

Same goes for `project` and `sleepdur`, I don't want to update the script everytime I want to change project.

**Comment by mrwbsn** [comment]
Hi! thanks for your feedback, I have added environment variable argument `PROJECT` and `SLEEP` to be filled before running the script, for more info please check README file. For GCloud binary location, the script should have automatically find the GCloud for now.
